# CMake generated Testfile for 
# Source directory: /workspaces/ai_cpp
# Build directory: /workspaces/ai_cpp/build-viewer
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(actuator_sim_component_check "/workspaces/ai_cpp/build-viewer/actuator_sim_component_check")
set_tests_properties(actuator_sim_component_check PROPERTIES  LABELS "actuator;simulation;unit" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;103;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(brain_common_check "/workspaces/ai_cpp/build-viewer/brain_common_check")
set_tests_properties(brain_common_check PROPERTIES  LABELS "brain;regression" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;109;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(brain_phase2_check "/workspaces/ai_cpp/build-viewer/brain_phase2_check")
set_tests_properties(brain_phase2_check PROPERTIES  LABELS "brain;regression" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;116;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(brain_phase3_4_check "/workspaces/ai_cpp/build-viewer/brain_phase3_4_check")
set_tests_properties(brain_phase3_4_check PROPERTIES  LABELS "brain;regression" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;119;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(brain_phase5_8_check "/workspaces/ai_cpp/build-viewer/brain_phase5_8_check")
set_tests_properties(brain_phase5_8_check PROPERTIES  LABELS "brain;regression" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;122;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_001_input_adapter "/workspaces/ai_cpp/build-viewer/ut_brn_mod_001_input_adapter")
set_tests_properties(ut_brn_mod_001_input_adapter PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;132;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_002_preprocess "/workspaces/ai_cpp/build-viewer/ut_brn_mod_002_preprocess")
set_tests_properties(ut_brn_mod_002_preprocess PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;133;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_003_world_state_manager "/workspaces/ai_cpp/build-viewer/ut_brn_mod_003_world_state_manager")
set_tests_properties(ut_brn_mod_003_world_state_manager PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;134;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_004_goal_manager "/workspaces/ai_cpp/build-viewer/ut_brn_mod_004_goal_manager")
set_tests_properties(ut_brn_mod_004_goal_manager PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;135;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_005_constraint_manager "/workspaces/ai_cpp/build-viewer/ut_brn_mod_005_constraint_manager")
set_tests_properties(ut_brn_mod_005_constraint_manager PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;136;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_006_memory_manager "/workspaces/ai_cpp/build-viewer/ut_brn_mod_006_memory_manager")
set_tests_properties(ut_brn_mod_006_memory_manager PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;137;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_007_policy_manager "/workspaces/ai_cpp/build-viewer/ut_brn_mod_007_policy_manager")
set_tests_properties(ut_brn_mod_007_policy_manager PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;138;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_008_planner "/workspaces/ai_cpp/build-viewer/ut_brn_mod_008_planner")
set_tests_properties(ut_brn_mod_008_planner PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;139;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_009_execution_manager "/workspaces/ai_cpp/build-viewer/ut_brn_mod_009_execution_manager")
set_tests_properties(ut_brn_mod_009_execution_manager PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;140;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_010_post_process "/workspaces/ai_cpp/build-viewer/ut_brn_mod_010_post_process")
set_tests_properties(ut_brn_mod_010_post_process PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;141;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_011_external_ai_adapter "/workspaces/ai_cpp/build-viewer/ut_brn_mod_011_external_ai_adapter")
set_tests_properties(ut_brn_mod_011_external_ai_adapter PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;142;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ut_brn_mod_012_log_trace_manager "/workspaces/ai_cpp/build-viewer/ut_brn_mod_012_log_trace_manager")
set_tests_properties(ut_brn_mod_012_log_trace_manager PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;143;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(it_brain_integration "/workspaces/ai_cpp/build-viewer/it_brain_integration")
set_tests_properties(it_brain_integration PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;144;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(brain_context_model_check "/workspaces/ai_cpp/build-viewer/brain_context_model_check")
set_tests_properties(brain_context_model_check PROPERTIES  LABELS "brain;spec" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;129;add_test;/workspaces/ai_cpp/CMakeLists.txt;145;add_brain_spec_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(discussion_check "/workspaces/ai_cpp/build-viewer/discussion_check")
set_tests_properties(discussion_check PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;156;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(discussion_agent_check "/workspaces/ai_cpp/build-viewer/discussion_agent_check")
set_tests_properties(discussion_agent_check PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;159;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ner_check "/workspaces/ai_cpp/build-viewer/ner_check")
set_tests_properties(ner_check PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;162;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(ner_conversion_check "/usr/bin/python3" "/workspaces/ai_cpp/tests/ner/test_convert_ner.py")
set_tests_properties(ner_conversion_check PROPERTIES  ENVIRONMENT "PYTHONDONTWRITEBYTECODE=1" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;165;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(discussion_data_check "/usr/bin/python3" "/workspaces/ai_cpp/tests/agent/test_generate_discussion_data.py")
set_tests_properties(discussion_data_check PROPERTIES  ENVIRONMENT "PYTHONDONTWRITEBYTECODE=1" _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;166;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(agent_check "/workspaces/ai_cpp/build-viewer/agent_check")
set_tests_properties(agent_check PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;172;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(control_flow_check "/workspaces/ai_cpp/build-viewer/control_flow_check")
set_tests_properties(control_flow_check PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;175;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
add_test(memory_migration_check "/workspaces/ai_cpp/build-viewer/memory_migration_check")
set_tests_properties(memory_migration_check PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/ai_cpp/CMakeLists.txt;178;add_test;/workspaces/ai_cpp/CMakeLists.txt;0;")
subdirs("_deps/mujoco-build")
subdirs("Simulation")
